### ISSUE TITLE
Lab #1

### ISSUE THREAD

**Issue by sandyacosta** [Watts-College/paf-513-fall-2023#3]
I am unable to knit and save to HTML, please help!

**Comment by drcarlson-asu** [comment]
Hi Sandy - I am unable to assist without seeing your work. Please provide screenshots (s) of the error received and the lines of code the error refers to.

**Comment by sandyacosta** [comment]
I was able to remove code chunks that R wasn't too happy with and was able to knit and save to Word but not HTML.

**Comment by sandyacosta** [comment]
![Screenshot 2023-08-27 161809](https://github.com/Watts-College/paf-513-fall-2023/assets/110320484/503c5595-e8b5-470e-a527-70e01f8bc408)

**Comment by drcarlson-asu** [comment]
That screenshot looks perfect. That is html. Just go to where your file is saved and your knitted HTML file will be there. Good job!

**Comment by sandyacosta** [comment]
Thanks!
