### ISSUE TITLE
Lab 1 Follow-up Question

### ISSUE THREAD

**Issue by Jcarbo7850** [Watts-College/paf-513-fall-2023#4]
Good afternoon professor - Both question 5 and 6 employ the function, which.max( ) but it only gives you the value position. What if we actually wanted to see the value in that position?

**Comment by lecy** [comment]
Should just be max()? 

I'm trying to remember the context but I think that is correct. 

```r
x <- c( 39, 97, 49, 72, 82 )
          #  ^
          # max

which.max(x)
[1] 2
max(x)
[1] 97
```
